# Target specific macros
TARGET = AlarmManualTest
TARGET_SOURCES = \
	./AlarmManualTest.c
TOPPERS_OSEK_OIL_SOURCE = ./AlarmManualTest.oil

O_PATH ?= build
ifndef NXTOSEK
    NXTOSEK = /usr/local/src/nxtosek
endif
include $(NXTOSEK)/ecrobot/ecrobot.mak

