# Target specific macros
TARGET = btinfo
TARGET_SOURCES = \
	btinfo.c
TOPPERS_OSEK_OIL_SOURCE = ./btinfo.oil

# Don't modify below part
O_PATH ?= build
ifndef NXTOSEK
    NXTOSEK = /usr/local/src/nxtosek
endif
include $(NXTOSEK)/ecrobot/ecrobot.mak
