echo Executing NeXTTool to upload /workspaces/nxtosek-3.01/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
wine ../bin/nexttool /COM=usb -firmware=/workspaces/nxtosek-3.01/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
