# Target specific macros
TARGET = mathtest
TARGET_SOURCES = \
	mathtest.c
TOPPERS_OSEK_OIL_SOURCE = ./mathtest.oil

# Don't modify below part
O_PATH ?= build
ifndef NXTOSEK
    NXTOSEK = /usr/local/src/nxtosek
endif
include $(NXTOSEK)/ecrobot/ecrobot.mak
