# Target specific macros
TARGET = CAL_H_COLOR
TARGET_SOURCES = ./cal_hitechcolor.c
TOPPERS_OSEK_OIL_SOURCE = ./cal_hitechcolor.oil

O_PATH ?= build
ifndef NXTOSEK
    NXTOSEK = /usr/local/src/nxtosek
endif
include $(NXTOSEK)/ecrobot/ecrobot.mak
