# Target specific macros
TARGET = NXT_COLOR
TARGET_SOURCES = \
	nxtcolorsensortest.c
TOPPERS_OSEK_OIL_SOURCE = ./nxtcolorsensortest.oil

# Don't modify below part
O_PATH ?= build
ifndef NXTOSEK
    NXTOSEK = /usr/local/src/nxtosek
endif
include $(NXTOSEK)/ecrobot/ecrobot.mak
